---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maximuss/public_html/
    - /bin/rsync -av --delete --exclude ".git" --exclude ".github" ./ $DEPLOYPATH

    # Set directory permissions
    - /usr/bin/find $DEPLOYPATH -type d -exec /bin/chmod 0755 {} \;
    
    # Set default file permissions
    - /usr/bin/find $DEPLOYPATH -type f -exec /bin/chmod 0644 {} \;
    
    # Set same permissions for PHP files (0644 for webserver access)
    - /usr/bin/find $DEPLOYPATH -type f -name "*.php" -exec /bin/chmod 0644 {} \;
    
    # Health check file
    - /bin/echo "ok" > $DEPLOYPATH/health.txt
    - /bin/chmod 0644 $DEPLOYPATH/health.txt

    # Deploy log
    - /bin/echo "Deploy OK $(/bin/date)" >> $DEPLOYPATH/deployment.log
    - /bin/chmod 0644 $DEPLOYPATH/deployment.log