---
deployment:
  tasks:
    - export DEPLOYPATH=/home/maximuss/public_html/
    - /bin/rsync -av --delete --exclude ".git" --exclude ".github" ./ $DEPLOYPATH

    # SAFE permissions – do NOT depend on group ownership
    - /usr/bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /usr/bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;

    # Health check file
    - /bin/echo "ok" > $DEPLOYPATH/health.txt
    - /bin/chmod 644 $DEPLOYPATH/health.txt

    # Deploy log (optional)
    - /bin/echo "Deploy OK $(/bin/date)" >> $DEPLOYPATH/deployment.log
    - /bin/chmod 644 $DEPLOYPATH/deployment.log